version: "2"
linters:
  default: standard
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"
        - "-S1039"
        - "-SA4010"
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
        - (io.Closer).Close
        - (*os.File).Close
        - (*io.PipeWriter).Close
        - (io.WriteCloser).Close
        - (*crypto/tls.Conn).Close
        - (net.Conn).Close
        - (net.Listener).Close
